export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_RESET = 'LOGIN_USER_RESET';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_ERROR = 'USER_EDIT_ERROR';
export const USER_EDIT_RESET = 'USER_EDIT_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_ERROR = 'USER_LIST_ERROR';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';
export const USER_GET_RESET = 'USER_GET_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const MULTI_DELETE_REQUEST = 'MULTI_DELETE_REQUEST';
export const MULTI_DELETE_SUCCESS = 'MULTI_DELETE_SUCCESS';
export const MULTI_DELETE_ERROR = 'MULTI_DELETE_ERROR';
export const MULTI_DELETE_RESET = 'MULTI_DELETE_RESET';

export const FORGOTPASSWORD_USER_REQUEST = 'FORGOTPASSWORD_USER_REQUEST';
export const FORGOTPASSWORD_USER_SUCCESS = 'FORGOTPASSWORD_USER_SUCCESS';
export const FORGOTPASSWORD_USER_ERROR = 'FORGOTPASSWORD_USER_ERROR';
export const FORGOTPASSWORD_USER_RESET = 'FORGOTPASSWORD_USER_RESET';

export const RESETPASSWORD_USER_REQUEST = 'RESETPASSWORD_USER_REQUEST';
export const RESETPASSWORD_USER_SUCCESS = 'RESETPASSWORD_USER_SUCCESS';
export const RESETPASSWORD_USER_ERROR = 'RESETPASSWORD_USER_ERROR';
export const RESETPASSWORD_USER_RESET = 'RESETPASSWORD_USER_RESET';

// chairman constants
export const CHAIRMAN_REGISTER_REQUEST = 'CHAIRMAN_REGISTER_REQUEST';
export const CHAIRMAN_REGISTER_SUCCESS = 'CHAIRMAN_REGISTER_SUCCESS';
export const CHAIRMAN_REGISTER_ERROR = 'CHAIRMAN_REGISTER_ERROR';
export const CHAIRMAN_REGISTER_RESET = 'CHAIRMAN_REGISTER_RESET';

export const CHAIRMAN_LIST_REQUEST = 'CHAIRMAN_LIST_REQUEST';
export const CHAIRMAN_LIST_SUCCESS = 'CHAIRMAN_LIST_SUCCESS';
export const CHAIRMAN_LIST_ERROR = 'CHAIRMAN_LIST_ERROR';
export const CHAIRMAN_LIST_RESET = 'CHAIRMAN_LIST_RESET';

export const CHAIRMAN_DELETE_REQUEST = 'CHAIRMAN_DELETE_REQUEST';
export const CHAIRMAN_DELETE_SUCCESS = 'CHAIRMAN_DELETE_SUCCESS';
export const CHAIRMAN_DELETE_ERROR = 'CHAIRMAN_DELETE_ERROR';
export const CHAIRMAN_DELETE_RESET = 'CHAIRMAN_DELETE_RESET';

//Complex constants

export const COMPLEX_LIST_REQUEST = 'COMPLEX_LIST_REQUEST';
export const COMPLEX_LIST_SUCCESS = 'COMPLEX_LIST_SUCCESS';
export const COMPLEX_LIST_ERROR = 'COMPLEX_LIST_ERROR';
export const COMPLEX_LIST_RESET = 'COMPLEX_LIST_RESET';

export const COMPLEX_GET_REQUEST = 'COMPLEX_GET_REQUEST';
export const COMPLEX_GET_SUCCESS = 'COMPLEX_GET_SUCCESS';
export const COMPLEX_GET_ERROR = 'COMPLEX_GET_ERROR';
export const COMPLEX_GET_RESET = 'COMPLEX_GET_RESET';

export const COMPLEX_CREATE_REQUEST = 'COMPLEX_CREATE_REQUEST';
export const COMPLEX_CREATE_SUCCESS = 'COMPLEX_CREATE_SUCCESS';
export const COMPLEX_CREATE_ERROR = 'COMPLEX_CREATE_ERROR';
export const COMPLEX_CREATE_RESET = 'COMPLEX_CREATE_RESET';

export const COMPLEX_EDIT_REQUEST = 'COMPLEX_EDIT_REQUEST';
export const COMPLEX_EDIT_SUCCESS = 'COMPLEX_EDIT_SUCCESS';
export const COMPLEX_EDIT_ERROR = 'COMPLEX_EDIT_ERROR';
export const COMPLEX_EDIT_RESET = 'COMPLEX_EDIT_RESET';

export const COMPLEX_DELETE_REQUEST = 'COMPLEX_DELETE_REQUEST';
export const COMPLEX_DELETE_SUCCESS = 'COMPLEX_DELETE_SUCCESS';
export const COMPLEX_DELETE_ERROR = 'COMPLEX_DELETE_ERROR';
export const COMPLEX_DELETE_RESET = 'COMPLEX_DELETE_RESET';

export const COMPLEX_MULTI_DELETE_REQUEST = 'COMPLEX_MULTI_DELETE_REQUEST';
export const COMPLEX_MULTI_DELETE_SUCCESS = 'COMPLEX_MULTI_DELETE_SUCCESS';
export const COMPLEX_MULTI_DELETE_ERROR = 'COMPLEX_MULTI_DELETE_ERROR';
export const COMPLEX_MULTI_DELETE_RESET = 'COMPLEX_MULTI_DELETE_RESET';

// vendor constants
export const VENDOR_REGISTER_REQUEST = 'VENDOR_REGISTER_REQUEST';
export const VENDOR_REGISTER_SUCCESS = 'VENDOR_REGISTER_SUCCESS';
export const VENDOR_REGISTER_ERROR = 'VENDOR_REGISTER_ERROR';
export const VENDOR_REGISTER_RESET = 'VENDOR_REGISTER_RESET';

export const VENDOR_GET_REQUEST = 'VENDOR_GET_REQUEST';
export const VENDOR_GET_SUCCESS = 'VENDOR_GET_SUCCESS';
export const VENDOR_GET_ERROR = 'VENDOR_GET_ERROR';
export const VENDOR_GET_RESET = 'VENDOR_GET_RESET';

export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST';
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS';
export const VENDOR_LIST_ERROR = 'VENDOR_LIST_ERROR';
export const VENDOR_LIST_RESET = 'VENDOR_LIST_RESET';

export const VENDOR_DELETE_REQUEST = 'VENDOR_DELETE_REQUEST';
export const VENDOR_DELETE_SUCCESS = 'VENDOR_DELETE_SUCCESS';
export const VENDOR_DELETE_ERROR = 'VENDOR_DELETE_ERROR';
export const VENDOR_DELETE_RESET = 'VENDOR_DELETE_RESET';

export const VENDOR_EDIT_REQUEST = 'VENDOR_EDIT_REQUEST';
export const VENDOR_EDIT_SUCCESS = 'VENDOR_EDIT_SUCCESS';
export const VENDOR_EDIT_ERROR = 'VENDOR_EDIT_ERROR';
export const VENDOR_EDIT_RESET = 'VENDOR_EDIT_RESET';

export const VENDOR_MULTI_DELETE_REQUEST = 'VENDOR_MULTI_DELETE_REQUEST';
export const VENDOR_MULTI_DELETE_SUCCESS = 'VENDOR_MULTI_DELETE_SUCCESS';
export const VENDOR_MULTI_DELETE_ERROR = 'VENDOR_MULTI_DELETE_ERROR';
export const VENDOR_MULTI_DELETE_RESET = 'VENDOR_MULTI_DELETE_RESET';




// Announcement constants

export const ANNOUNCEMENT_REGISTER_REQUEST = 'ANNOUNCEMENT_REGISTER_REQUEST';
export const ANNOUNCEMENT_REGISTER_SUCCESS = 'ANNOUNCEMENT_REGISTER_SUCCESS';
export const ANNOUNCEMENT_REGISTER_ERROR = 'ANNOUNCEMENT_REGISTER_ERROR';
export const ANNOUNCEMENT_REGISTER_RESET = 'ANNOUNCEMENT_REGISTER_RESET';

export const ANNOUNCEMENT_GET_REQUEST = 'ANNOUNCEMENT_GET_REQUEST';
export const ANNOUNCEMENT_GET_SUCCESS = 'ANNOUNCEMENT_GET_SUCCESS';
export const ANNOUNCEMENT_GET_ERROR = 'ANNOUNCEMENT_GET_ERROR';
export const ANNOUNCEMENT_GET_RESET = 'ANNOUNCEMENT_GET_RESET';

export const ANNOUNCEMENT_LIST_REQUEST = 'ANNOUNCEMENT_LIST_REQUEST';
export const ANNOUNCEMENT_LIST_SUCCESS = 'ANNOUNCEMENT_LIST_SUCCESS';
export const ANNOUNCEMENT_LIST_ERROR = 'ANNOUNCEMENT_LIST_ERROR';
export const ANNOUNCEMENT_LIST_RESET = 'ANNOUNCEMENT_LIST_RESET';

export const ANNOUNCEMENT_DELETE_REQUEST = 'ANNOUNCEMENT_DELETE_REQUEST';
export const ANNOUNCEMENT_DELETE_SUCCESS = 'ANNOUNCEMENT_DELETE_SUCCESS';
export const ANNOUNCEMENT_DELETE_ERROR = 'ANNOUNCEMENT_DELETE_ERROR';
export const ANNOUNCEMENT_DELETE_RESET = 'ANNOUNCEMENT_DELETE_RESET';

export const ANNOUNCEMENT_EDIT_REQUEST = 'ANNOUNCEMENT_EDIT_REQUEST';
export const ANNOUNCEMENT_EDIT_SUCCESS = 'ANNOUNCEMENT_EDIT_SUCCESS';
export const ANNOUNCEMENT_EDIT_ERROR = 'ANNOUNCEMENT_EDIT_ERROR';
export const ANNOUNCEMENT_EDIT_RESET = 'ANNOUNCEMENT_EDIT_RESET';

export const ANNOUNCEMENT_MULTI_DELETE_REQUEST = 'ANNOUNCEMENT_MULTI_DELETE_REQUEST';
export const ANNOUNCEMENT_MULTI_DELETE_SUCCESS = 'ANNOUNCEMENT_MULTI_DELETE_SUCCESS';
export const ANNOUNCEMENT_MULTI_DELETE_ERROR = 'ANNOUNCEMENT_MULTI_DELETE_ERROR';
export const ANNOUNCEMENT_MULTI_DELETE_RESET = 'ANNOUNCEMENT_MULTI_DELETE_RESET';